language: python
python:
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
# command to install dependencies
#
install:
  - pip install -r requirements/requirements.txt
# command to run tests
script:
  - pytest -s -v # or py.test for Python versions 3.5 and below
